global:
  scrape_interval: 15s  # 기본 데이터 수집 주기
  evaluation_interval: 15s  # 알람 평가 주기
  scrape_timeout: 10s  # 최대 데이터 수집 시간

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093'] 
rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus 자체 모니터링
  - job_name: 'node_exporter'
    static_configs:
      # Node Exporter 추가 (옵션), node-exporter는 컨테이너 이름
      - targets: ['node-exporter:9100']  
  - job_name: 'cloudwatch-exporter'
    static_configs:
      - targets: ['cloudwatch-exporter:9106']


